In [1]:
# find max sub array
def maxsubarray(arr):
    min_sum = 0
    max_sum = 0
    min_idx = -1
    max_idx = 0
    total_sum = 0
    best_range= [None, None]
    for idx, item in enumerate(arr):
        total_sum+=item
        if total_sum < min_sum:
            min_sum = total_sum
            min_idx = idx
        if total_sum - min_sum > max_sum:
            max_sum = total_sum-min_sum
            best_range=[min_idx, idx+1]
    return best_range

x = [10, 20, -100, 50, 400, -1]
maxsubarray(x)

[2, 5]

In [53]:
import numpy as np
def edit_distance(s1, s2):
    dp_table = np.array([[0 for i in range(len(s2)+1)] for j in range(len(s1)+1) ])
    for i in range(len(s2)+1):
        dp_table[0][i] = 1
    for i in range(len(s1)+1):
        dp_table[i][0] = 1
        
    for i in range(0, len(s1)):
        for j in range(0,len(s2)):
            min_val = min([dp_table[i-1+1][j-1+1], dp_table[i-1+1][j+1], dp_table[i+1][j-1+1]])
            if s1[i] == s2[j]:
                dp_table[i+1][j+1] = min_val
            else:
                dp_table[i+1][j+1]= min_val+1
    print(dp_table)
    return dp_table[-1][-1]

edit_distance('dimple', 'ample')

[[1 1 1 1 1 1]
 [1 2 2 2 2 2]
 [1 2 3 3 3 3]
 [1 2 2 3 4 4]
 [1 2 3 2 3 4]
 [1 2 3 3 2 3]
 [1 2 3 4 3 2]]


2

In [27]:
coins = [5, 10, 5, 15, 20, 10] #5,20,10      10,15,5
def pickupCoinsMaxGain(coins):
    dp = [[(0,0) for i in range(len(coins))] for j in range(len(coins))]
    
    for i in range(len(coins)):
        dp[i][i] = (coins[i],0)
    
    for l in range(2, len(coins)+1):
        for i in range(0, len(coins)-l+1):
            j = l+i-1
            pick_a = coins[i] + dp[i+1][j][1]
            pick_b = coins[j] + dp[i][j-1][1]
            if pick_a > pick_b:
                dp[i][j] = (pick_a, dp[i+1][j][0])
            else:
                dp[i][j] = (pick_b, dp[i][j-1][0])
    for row in dp:
        print(row)
pickupCoinsMaxGain(coins)

[(5, 0), (10, 5), (10, 10), (25, 10), (30, 25), (35, 30)]
[(0, 0), (10, 0), (10, 5), (20, 10), (30, 20), (35, 25)]
[(0, 0), (0, 0), (5, 0), (15, 5), (25, 15), (25, 25)]
[(0, 0), (0, 0), (0, 0), (15, 0), (20, 15), (25, 20)]
[(0, 0), (0, 0), (0, 0), (0, 0), (20, 0), (20, 10)]
[(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (10, 0)]


In [29]:
def knapsack(items, max_weight):
    dp = [0 for i in range(max_weight+1)]
    for item in items:
        j = max_weight
        while j >= item[1]:
            dp[j] = max(dp[j], dp[j-item[1]] + item[0])
            j-=1
            
    return dp[max_weight]

knapsack([(10,5), (14,6),(8,2), (7, 3)], max_weight=5) #(value, weight)

15

In [35]:
def is_match(arr, s, arr_idx, arr_idy, s_idx, cache):
    if s_idx == len(s):
        return True
    if s_idx <0 or s_idx > len(s) or \
       arr_idx <0 or arr_idx>len(arr) or arr_idy>len(arr[arr_idx]) or\
      (arr_idx, arr_idy, s_idx ) in cache:
        return False
    if s[s_idx] != arr[arr_idx][arr_idy]:
        return False
    
    if s[s_idx] == arr[arr_idx][arr_idy] and \
       (is_match(arr, s, arr_idx+1, arr_idy, s_idx+1, cache) or\
        is_match(arr, s, arr_idx-1, arr_idy, s_idx+1, cache) or\
        is_match(arr, s, arr_idx, arr_idy+1, s_idx+1, cache) or\
        is_match(arr, s, arr_idx, arr_idy-1, s_idx+1, cache)):
        return True
    cache.append((arr_idx, arr_idy, s_idx))
    return False
    
def search_sequence_in_array(arr, s):
    return is_match(arr, s, 0, 0, 0, [])
    
arr = [[1,2,3], [3,4,5], [5,6,7]]
s = [1,3,4,7]
search_sequence_in_array(arr, s)

False

In [47]:
def count_number_of_steps(n, k):
    steps = [0 for i in range(k+1)]
    steps[0] =1 
    steps[1] =1
    for i in range(2, n+1):
        steps[i%(k+1)] = 0
        j = 1
        while j <=k and i-j >= 0:
            print(i, j, (i-j)%(k+1))
            steps[i%(k+1)] += steps[(i-j)%(k+1)]
            j+=1
        print('---')
    print(steps)
    return steps[n%(k+1)]


# def count_number_of_steps(n, k):
#     steps = [0 for i in range(k+1)]
#     steps[0] =1 
#     for step in range(len(steps)):
#         for i in range(step, len(steps)):
#             steps[i] += steps[i-step]
#             i+=1
#     print(steps)
#     return steps[-1]
count_number_of_steps(n=5, k=2)

2 1 1
2 2 0
---
3 1 2
3 2 1
---
4 1 0
4 2 2
---
5 1 1
5 2 0
---
[3, 5, 8]


8

In [51]:
a=[1,2,3]
for i in range(1,5):
    print(i)

1
2
3
4
