In [1]:
# find max sub array
def maxsubarray(arr):
    min_sum = 0
    max_sum = 0
    min_idx = -1
    max_idx = 0
    total_sum = 0
    best_range= [None, None]
    for idx, item in enumerate(arr):
        total_sum+=item
        if total_sum < min_sum:
            min_sum = total_sum
            min_idx = idx
        if total_sum - min_sum > max_sum:
            max_sum = total_sum-min_sum
            best_range=[min_idx, idx+1]
    return best_range

x = [10, 20, -100, 50, 400, -1]
maxsubarray(x)

[2, 5]

In [53]:
import numpy as np
def edit_distance(s1, s2):
    dp_table = np.array([[0 for i in range(len(s2)+1)] for j in range(len(s1)+1) ])
    for i in range(len(s2)+1):
        dp_table[0][i] = 1
    for i in range(len(s1)+1):
        dp_table[i][0] = 1
        
    for i in range(0, len(s1)):
        for j in range(0,len(s2)):
            min_val = min([dp_table[i-1+1][j-1+1], dp_table[i-1+1][j+1], dp_table[i+1][j-1+1]])
            if s1[i] == s2[j]:
                dp_table[i+1][j+1] = min_val
            else:
                dp_table[i+1][j+1]= min_val+1
    print(dp_table)
    return dp_table[-1][-1]

edit_distance('dimple', 'ample')

[[1 1 1 1 1 1]
 [1 2 2 2 2 2]
 [1 2 3 3 3 3]
 [1 2 2 3 4 4]
 [1 2 3 2 3 4]
 [1 2 3 3 2 3]
 [1 2 3 4 3 2]]


2